services:
    api:
      build: .
      restart: always
      command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --ini liveconfidence-project-uwsgi.ini"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
  